name: Déploiement Continu belemb.eu

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4.2.0

      - name: Configuration de Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22
          cache: 'npm'

      - name: Installation et Build
        run: |
          npm ci
          npm run build

      - name: Sauvegarder le dossier build
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: ./dist/
          retention-days: 1 

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
       dossier-cible:
          - "./sites/belemb.eu/"
          - "./sites/belemb.eu/mission-economique-conakry/"
          - "./sites/belemb.eu/mission-economique-belge-au-senegal/"
          - "./sites/belemb.eu/mission-to-kenya/"
          - "./sites/belemb.eu/mission-to-gambia/"
          - "./sites/belemb.eu/mission-to-tanzania/"


    steps:
      - name: Récupérer le dossier build
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: ./dist/

      - name: Déploiement SFTP sur ${{ matrix.dossier-cible }}
        uses: lpresswood/sftp-deploy-action@v1.1.2
        with:
          server: pw0lr.ftp.infomaniak.com  # <-- SANS sftp:// devant
          username: pw0lr_sitebelge
          password: ${{ secrets.INFOMANIAK_SFTP_PASSWORD }}
          port: 22  # Le port SFTP standard est le 22 (au lieu de 21)
          local-dir: ./dist/
          server-dir: ${{ matrix.dossier-cible }}
