name: Déploiement Continu Production belemb.eu

on:
  push:
    branches:
      - main # Déclenchement uniquement sur la branche officielle

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4.2.0

      - name: Configuration de Node.js 24
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 24
          cache: 'npm' # Active la mise en cache native des dépendances GitHub

      - name: Installation propre des dépendances et Build
        run: |
          npm ci
          npm run build

      - name: Vérification du dossier dist
        run: ls -la dist

      - name: Déploiement automatisé sécurisé sur Infomaniak
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ://infomaniak.com
          username: pw0lr_sitebelge
          password: ${{ secrets.INFOMANIAK_SFTP_PASSWORD }}
          port: 21
          protocol: ftps
          local-dir: ./dist/
          server-dir: ./sites/belemb.eu/
